require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'app/channels/application_cable/*'
    - 'app/helpers/*'
    - 'app/jobs/*'
    - 'app/mailers/*'
    - 'bin/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'lib/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config.ru'
    - 'Rakefile'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/ClassVars:
  Enabled: false

ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/users/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/tables_controller.rb'
    - 'app/controllers/users/registrations_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/tables_controller.rb'
    - 'app/controllers/users/registrations_controller.rb'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'
